import type { Metadata } from "next";
import { JetBrains_Mono } from 'next/font/google'
import "./globals.css";


const jetbrains_mono = JetBrains_Mono({
  weight: '500',
  subsets: ['latin'],
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jetbrains_mono.className}>{children}</body>
    </html>
  );
}
