import type { Metadata } from "next";
import { JetBrains_Mono } from 'next/font/google'
import "./globals.css";
import Header from './components/Header';


const jetbrains_mono = JetBrains_Mono({
  weight: '500',
  subsets: ['latin'],
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jetbrains_mono.className}>
        <main className="flex min-h-screen flex-col items-center justify-between py-6 px-[200px]">
          <Header/>
          {children}
        </main>
      </body>
    </html>
  );
}
